version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: MangaScrapper/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoSettings__ConnectionString=mongodb://mongodb:27017
      - MongoSettings__DatabaseName=manga-scrap
      - ScrapperSettings__ImageStoragePath=/app/images
      - ScrapperSettings__MaxParallelDownloads=10
    volumes:
      - ./images:/app/images
      - ./MangaScrapper/provider:/app/provider:ro
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=manga-scrap

volumes:
  mongo-data:
